"""Updated Miembro model

Revision ID: 3ca784b21cb6
Revises: a59b989839f1
Create Date: 2024-04-23 19:42:17.823187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca784b21cb6'
down_revision: Union[str, None] = 'a59b989839f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miembro', sa.Column('especialidad', sa.String(length=50), nullable=True))
    op.add_column('miembro', sa.Column('oracion', sa.String(length=50), nullable=True))
    op.add_column('miembro', sa.Column('fotografia', sa.String(length=50), nullable=True))
    op.add_column('miembro', sa.Column('fechaDeBautismo', sa.Date(), nullable=True))
    op.add_column('miembro', sa.Column('fechaDeEspirituSanto', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miembro', 'fechaDeEspirituSanto')
    op.drop_column('miembro', 'fechaDeBautismo')
    op.drop_column('miembro', 'fotografia')
    op.drop_column('miembro', 'oracion')
    op.drop_column('miembro', 'especialidad')
    # ### end Alembic commands ###
