"""Added new fields to Miembro

Revision ID: 4408edb7fa2e
Revises: 
Create Date: 2024-03-28 17:31:48.821392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4408edb7fa2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direccion')
    op.add_column('miembro', sa.Column('horarioTrabajo', sa.String(length=50), nullable=True))
    op.add_column('miembro', sa.Column('salario', sa.Integer(), nullable=True))
    op.add_column('miembro', sa.Column('fechaIngreso', sa.Date(), nullable=True))
    op.add_column('miembro', sa.Column('antiguedad', sa.Integer(), nullable=True))
    op.drop_column('miembro', 'idDireccion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miembro', sa.Column('idDireccion', sa.INTEGER(), nullable=True))
    op.drop_column('miembro', 'antiguedad')
    op.drop_column('miembro', 'fechaIngreso')
    op.drop_column('miembro', 'salario')
    op.drop_column('miembro', 'horarioTrabajo')
    op.create_table('direccion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('calle', sa.VARCHAR(length=50), nullable=False),
    sa.Column('numero', sa.VARCHAR(length=50), nullable=False),
    sa.Column('colonia', sa.VARCHAR(length=50), nullable=False),
    sa.Column('municipio', sa.VARCHAR(length=50), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), nullable=False),
    sa.Column('cp', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
