"""Added new fields to Miembro

Revision ID: 6c3e39d5de5a
Revises: 4408edb7fa2e
Create Date: 2024-03-28 17:32:31.390057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c3e39d5de5a'
down_revision: Union[str, None] = '4408edb7fa2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miembro', 'antiguedad')
    op.drop_column('miembro', 'salario')
    op.drop_column('miembro', 'fechaIngreso')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miembro', sa.Column('fechaIngreso', sa.DATE(), nullable=True))
    op.add_column('miembro', sa.Column('salario', sa.INTEGER(), nullable=True))
    op.add_column('miembro', sa.Column('antiguedad', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
