"""Descripción de los cambios

Revision ID: 7e5e0132a2b3
Revises: 3ca784b21cb6
Create Date: 2024-04-30 12:40:21.317065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5e0132a2b3'
down_revision: Union[str, None] = '3ca784b21cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miembro', sa.Column('lugarDeBautismo', sa.String(length=50), nullable=True))
    op.add_column('miembro', sa.Column('lugarDeEspirituSanto', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miembro', 'lugarDeEspirituSanto')
    op.drop_column('miembro', 'lugarDeBautismo')
    # ### end Alembic commands ###
