"""Added new fields to Miembro

Revision ID: a59b989839f1
Revises: 6c3e39d5de5a
Create Date: 2024-03-29 14:00:28.020499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59b989839f1'
down_revision: Union[str, None] = '6c3e39d5de5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miembro', 'puesto')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miembro', sa.Column('puesto', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
